import thucdonbian from "../../asset/images/thucdonbian.jpg";

const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "upcoming",
    vibe: 15.99,
    img: thucdonbian,
    time: "116 phút",
    date: "18/11/2022",
  },
  {
    id: 2,
    title: "diner double",
    category: "showing",
    vibe: 13.99,
    img: thucdonbian,
    time: "116 phút",
    date: "18/11/2022",
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "especially",
    vibe: 6.99,
    img: thucdonbian,
    time: "116 phút",
    date: "18/11/2022",
  },
  {
    id: 4,
    title: "country delight",
    category: "showing",
    vibe: 20.99,
    img: thucdonbian,
    time: "116 phút",
    date: "18/11/2022",
  },
  {
    id: 5,
    title: "egg attack",
    category: "showing",
    vibe: 22.99,
    img: thucdonbian,
    time: "116 phút",
    date: "18/11/2022",
  },
  {
    id: 6,
    title: "oreo dream",
    category: "showing",
    vibe: 18.99,
    img: thucdonbian,
    time: "116 phút",
    date: "18/11/2022",
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "upcoming",
    vibe: 8.99,
    img: thucdonbian,
    time: "116 phút",
    date: "18/11/2022",
  },
  {
    id: 8,
    title: "american classic",
    category: "upcoming",
    vibe: 12.99,
    img: thucdonbian,
    time: "116 phút",
    date: "18/11/2022",
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "especially",
    vibe: 16.99,
    img: thucdonbian,
    time: "116 phút",
    date: "18/11/2022",
  },
];
export default menu;
